### ISSUE TITLE
Summoning friendly scorch causing game to instantly crash

### ISSUE THREAD

**Issue by KrystalTheFox** [Polarice3/FireNBlood#4]
I do apologize for another issue so soon but I spawned in the friendly scorch using /summon and as soon as a summoned it, the game instantly crashed. The crash was a ticking entity crash.

Forge version: 1.16.5 36.2.28
Mod version: Latest
How to reproduce crash: type /summon firenblood:friendly_scorch
Crash report: https://pastebin.com/T0gBye6m

**Comment by Polarice3** [comment]
Thank you for notifying me about this problem! I'll see what I can do! This mob is experimental so it's not properly implemented yet! The next update should be coming soon!
